/**
 * @fileoverview gRPC-Web generated client stub for trafficupdaterevents.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: backend/trafficupdaterevents/v1/events.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.trafficupdaterevents = {};
proto.trafficupdaterevents.v1 = require('./events_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.trafficupdaterevents.v1.TrafficUpdateEventsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.trafficupdaterevents.v1.TrafficUpdateEventsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsRequest,
 *   !proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsResponse>}
 */
const methodDescriptor_TrafficUpdateEventsService_StreamTrafficUpdateEvents = new grpc.web.MethodDescriptor(
  '/trafficupdaterevents.v1.TrafficUpdateEventsService/StreamTrafficUpdateEvents',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsRequest,
  proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsResponse,
  /**
   * @param {!proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsResponse.deserializeBinary
);


/**
 * @param {!proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsResponse>}
 *     The XHR Node Readable Stream
 */
proto.trafficupdaterevents.v1.TrafficUpdateEventsServiceClient.prototype.streamTrafficUpdateEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/trafficupdaterevents.v1.TrafficUpdateEventsService/StreamTrafficUpdateEvents',
      request,
      metadata || {},
      methodDescriptor_TrafficUpdateEventsService_StreamTrafficUpdateEvents);
};


/**
 * @param {!proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.trafficupdaterevents.v1.StreamTrafficUpdateEventsResponse>}
 *     The XHR Node Readable Stream
 */
proto.trafficupdaterevents.v1.TrafficUpdateEventsServicePromiseClient.prototype.streamTrafficUpdateEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/trafficupdaterevents.v1.TrafficUpdateEventsService/StreamTrafficUpdateEvents',
      request,
      metadata || {},
      methodDescriptor_TrafficUpdateEventsService_StreamTrafficUpdateEvents);
};


module.exports = proto.trafficupdaterevents.v1;

