// source: backend/cultureeventsmanagement/v1/events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.cultureeventsmanagement.v1.CulturalEventsEntry', null, global);
goog.exportSymbol('proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest', null, global);
goog.exportSymbol('proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.repeatedFields_, null);
};
goog.inherits(proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.displayName = 'proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.repeatedFields_, null);
};
goog.inherits(proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.displayName = 'proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cultureeventsmanagement.v1.CulturalEventsEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cultureeventsmanagement.v1.CulturalEventsEntry.displayName = 'proto.cultureeventsmanagement.v1.CulturalEventsEntry';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
areasList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest;
  return proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAreas(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAreasList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string areas = 1;
 * @return {!Array<string>}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.prototype.getAreasList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} returns this
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.prototype.setAreasList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} returns this
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.prototype.addAreas = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} returns this
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest.prototype.clearAreasList = function() {
  return this.setAreasList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
timestamp: jspb.Message.getFieldWithDefault(msg, 2, 0),
culturalEventsList: jspb.Message.toObjectList(msg.getCulturalEventsList(),
    proto.cultureeventsmanagement.v1.CulturalEventsEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse;
  return proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 3:
      var value = new proto.cultureeventsmanagement.v1.CulturalEventsEntry;
      reader.readMessage(value,proto.cultureeventsmanagement.v1.CulturalEventsEntry.deserializeBinaryFromReader);
      msg.addCulturalEvents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getCulturalEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.cultureeventsmanagement.v1.CulturalEventsEntry.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse} returns this
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 timestamp = 2;
 * @return {number}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse} returns this
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated CulturalEventsEntry cultural_events = 3;
 * @return {!Array<!proto.cultureeventsmanagement.v1.CulturalEventsEntry>}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.getCulturalEventsList = function() {
  return /** @type{!Array<!proto.cultureeventsmanagement.v1.CulturalEventsEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cultureeventsmanagement.v1.CulturalEventsEntry, 3));
};


/**
 * @param {!Array<!proto.cultureeventsmanagement.v1.CulturalEventsEntry>} value
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse} returns this
*/
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.setCulturalEventsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.cultureeventsmanagement.v1.CulturalEventsEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry}
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.addCulturalEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.cultureeventsmanagement.v1.CulturalEventsEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse} returns this
 */
proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.prototype.clearCulturalEventsList = function() {
  return this.setCulturalEventsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.cultureeventsmanagement.v1.CulturalEventsEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
eventDate: jspb.Message.getFieldWithDefault(msg, 1, ""),
eventTime: jspb.Message.getFieldWithDefault(msg, 2, ""),
title: jspb.Message.getFieldWithDefault(msg, 3, ""),
venue: jspb.Message.getFieldWithDefault(msg, 4, ""),
area: jspb.Message.getFieldWithDefault(msg, 5, ""),
category: jspb.Message.getFieldWithDefault(msg, 6, ""),
price: jspb.Message.getFieldWithDefault(msg, 7, ""),
link: jspb.Message.getFieldWithDefault(msg, 8, ""),
description: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cultureeventsmanagement.v1.CulturalEventsEntry;
  return proto.cultureeventsmanagement.v1.CulturalEventsEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventDate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventTime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setVenue(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setArea(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrice(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setLink(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cultureeventsmanagement.v1.CulturalEventsEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventDate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEventTime();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getVenue();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getArea();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPrice();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getLink();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string event_date = 1;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getEventDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setEventDate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string event_time = 2;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getEventTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setEventTime = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string venue = 4;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getVenue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setVenue = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string area = 5;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getArea = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setArea = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string category = 6;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string price = 7;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string link = 8;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setLink = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string description = 9;
 * @return {string}
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.cultureeventsmanagement.v1.CulturalEventsEntry} returns this
 */
proto.cultureeventsmanagement.v1.CulturalEventsEntry.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


goog.object.extend(exports, proto.cultureeventsmanagement.v1);
