/**
 * @fileoverview gRPC-Web generated client stub for cultureeventsmanagement.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: backend/cultureeventsmanagement/v1/events.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.cultureeventsmanagement = {};
proto.cultureeventsmanagement.v1 = require('./events_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cultureeventsmanagement.v1.CulturalEventsManagementServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cultureeventsmanagement.v1.CulturalEventsManagementServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest,
 *   !proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse>}
 */
const methodDescriptor_CulturalEventsManagementService_StreamCulturalEventsManagementEvents = new grpc.web.MethodDescriptor(
  '/cultureeventsmanagement.v1.CulturalEventsManagementService/StreamCulturalEventsManagementEvents',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest,
  proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse,
  /**
   * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse.deserializeBinary
);


/**
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse>}
 *     The XHR Node Readable Stream
 */
proto.cultureeventsmanagement.v1.CulturalEventsManagementServiceClient.prototype.streamCulturalEventsManagementEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cultureeventsmanagement.v1.CulturalEventsManagementService/StreamCulturalEventsManagementEvents',
      request,
      metadata || {},
      methodDescriptor_CulturalEventsManagementService_StreamCulturalEventsManagementEvents);
};


/**
 * @param {!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cultureeventsmanagement.v1.StreamCulturalEventsManagementEventsResponse>}
 *     The XHR Node Readable Stream
 */
proto.cultureeventsmanagement.v1.CulturalEventsManagementServicePromiseClient.prototype.streamCulturalEventsManagementEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cultureeventsmanagement.v1.CulturalEventsManagementService/StreamCulturalEventsManagementEvents',
      request,
      metadata || {},
      methodDescriptor_CulturalEventsManagementService_StreamCulturalEventsManagementEvents);
};


module.exports = proto.cultureeventsmanagement.v1;

